### ISSUE TITLE
Update deps to fix security issue

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [CommercialTribe/simple-todo#1]
https://github.com/CommercialTribe/simple-todo/network/alerts

**Comment by jacobcabantomski-ct** [comment]
FYI @cdriscol , should fix this before next coding interview exercise :)

**Comment by cdriscol** [comment]
fixed with https://github.com/CommercialTribe/simple-todo/commit/100bcfdc5648e8571b7c689f9e95a3c83bf6f883
